id = "genzimnify"
name = "Genzimnify"
description = "Gen Z slang transpiles to Python. If it vibes, it compiles. Syntax highlighting (tree-sitter) + gzim-lsp integration: diagnostics, hover, go-to-definition, completion, symbols."
version = "0.1.0"
schema_version = 1
authors = ["Genzimnify"]
repository = "https://github.com/wendellmeset/Genzimnify"
languages = ["languages/genzimnify"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.genzimnify]
repository = "https://github.com/wendellmeset/Genzimnify"
rev = "3efef3ee20a87dc9e3ddcdfdf53d136c9d54d82c"
path = "grammars/genzimnify"

[language_servers.gzim-lsp]
languages = ["Genzimnify"]
